### ISSUE TITLE
s:verb does not prevent replacement of endash/emdash

### ISSUE THREAD

**Issue by johndoe31415** [johndoe31415/pyradium#56]
When in a `s:verb` environment, we want to disable rendering of endash and emdash. For example, when showing morse code as `<s:verb>---</s:verb>`, this should be shown as three distinct dashes. Recursive descent in https://github.com/johndoe31415/pyradium/blob/18176d648d15e508d72b2ed255e8ced43e24f02a/pyradium/xmlhooks/XMLHookRegistry.py#L75 prevents this currently.

**Comment by niri81** [comment]
That's working for me though. I changed the walk method to make this a default value:
```py
def walk(cls, node, callback, predicate = None, cancel_descent_predicate = lambda node: node.nodeName == "s:verb"):
```
<img width="822" alt="image" src="https://github.com/johndoe31415/pyradium/assets/38499069/c7ed84dc-b278-44d1-9670-0d60f1a1db70">
<img width="864" alt="image" src="https://github.com/johndoe31415/pyradium/assets/38499069/7d835470-55d0-4dfb-82c2-32680144dfbb">

**Comment by johndoe31415** [comment]
Should now be fixed, explanation see https://github.com/johndoe31415/pyradium/pull/57#issuecomment-1779947480
