### ISSUE TITLE
Remove visible border around slides in fullscreen mode

### ISSUE THREAD

**Issue by tametsi** [johndoe31415/pyradium#58]
I've noticed a little imperfection that really bothers me: When viewing the slides in "normal mode" there are beautiful borders around the slides <3, but this border https://github.com/johndoe31415/pyradium/blob/6fc7f5bb923bce8be30dcbac41d98e146278bb20/pyradium/templates/base/pyradium.css#L8 remains visible when entering fullscreen/presentation mode.

This might not be a big deal on a monitor, but creates the illusion of having a not touching-the-edges bottom bar on the slides on a projector in fullscreen mode.

The reason for this is that the fullscreen container https://github.com/johndoe31415/pyradium/blob/da26eee71599a062c38f58e2150dda8e9adb86b2/pyradium/templates/base/index.html#L93 has the very same style as the container for a single slide (`.size_container`), including the awesome border.

**Comment by johndoe31415** [comment]
Good catch, would you want to create a PR for that? It should be easily fixable somewhere in the template CSS. I'm sure there's also differentiation between presentation mode and non-presentation mode because at least the mouse cursor and style of links ("<a>" tag) is different.
